"use client";

import { useState } from "react";
import { Card } from "@/components/ui/Card";
import { Field } from "@/components/ui/Field";
import { DatePicker } from "@/components/ui/DatePicker";
import { Select } from "@/components/ui/Select";
import { DATASET_OPTIONS, FORMAT_OPTIONS } from "@/lib/data/labels";
import { exportHref } from "@/lib/data/client";
import type { DataDataset, DataFormat } from "@/lib/data/types";

/**
 * ExportPanel — export a dataset to CSV/Excel over an optional date range. The download
 * streams through the authenticated proxy (Bearer added server-side), so it's a plain
 * anchor — no token in the URL.
 */
export function ExportPanel() {
  const [dataset, setDataset] = useState<DataDataset>("emissions");
  const [format, setFormat] = useState<DataFormat>("csv");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  return (
    <Card className="space-y-4">
      <div className="grid gap-4 sm:grid-cols-2">
        <Select label="Dataset" options={DATASET_OPTIONS} value={dataset} onChange={(v) => setDataset(v as DataDataset)} />
        <Select label="Format" options={FORMAT_OPTIONS} value={format} onChange={(v) => setFormat(v as DataFormat)} />
        <Field id="export-from" label="From" hint="Optional">
          <DatePicker value={from} onChange={setFrom} />
        </Field>
        <Field id="export-to" label="To" hint="Optional">
          <DatePicker value={to} onChange={setTo} />
        </Field>
      </div>

      <a
        href={exportHref(dataset, format, from || undefined, to || undefined)}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1.5 rounded-md bg-accent px-4 py-2 text-sm font-medium text-accent-contrast transition-colors hover:bg-accent-hover"
      >
        Export {FORMAT_OPTIONS.find((f) => f.value === format)?.label}
      </a>
      <p className="text-xs text-faint">The file is generated by the backend and downloaded through the secure proxy.</p>
    </Card>
  );
}
