import type { Metadata } from "next";
import { ReportsWorkspace } from "@/components/reports/ReportsWorkspace";

export const metadata: Metadata = {
  title: "Reports",
};

/**
 * /app/reports — configure and generate multi-framework reports (GHG Protocol, NUPRC
 * GHGEMP, OGMP 2.0, CSRD/ISSB, TCFD, PCAF), export to PDF/Excel (backend file-generation),
 * with summary KPIs and a copilot board-ESG-summary pre-seed. All figures + files from the
 * backend.
 */
export default function ReportsPage() {
  return (
    <div className="mx-auto max-w-7xl">
      <div className="mb-6">
        <h1 className="text-xl font-semibold tracking-tight text-primary">Reports</h1>
        <p className="mt-1 text-sm text-secondary">
          Audit-ready, multi-framework reporting — configured here, generated by the engine,
          exported to PDF or Excel.
        </p>
      </div>
      <ReportsWorkspace />
    </div>
  );
}
