import type { Metadata } from "next";
import { AnalyticsWorkspace } from "@/components/analytics/AnalyticsWorkspace";

export const metadata: Metadata = {
  title: "Analytics",
};

/**
 * /app/analytics — emissions trend (bar/line/area + forecast band), period-over-period
 * comparison, scope breakdown, intensity KPIs, and AI insight cards generated by the
 * copilot from the actual data (clearly marked). All figures from the backend.
 */
export default function AnalyticsPage() {
  return (
    <div className="mx-auto max-w-7xl">
      <div className="mb-6">
        <h1 className="text-xl font-semibold tracking-tight text-primary">Analytics</h1>
        <p className="mt-1 text-sm text-secondary">
          Trends, breakdowns and intensity across your emissions — with AI insights on what’s
          driving them.
        </p>
      </div>
      <AnalyticsWorkspace />
    </div>
  );
}
